import React, {useEffect, useState} from 'react';
import UpDown from "./UpDown";
import {validateSide} from "../assets/utils/utils";
import HalfLine from "./HalfLine";
import FileSelector from "./FileSelector";



export default function CompLine({font, setter, contentIndex, setContentIndex, glyphIndex, setGlyphIndex, cmd, setCmd, file, setFile}) {
    const [updating, setUpdating] = useState(false)
    
    const updateGlyphIndex = (side, font, contentIndex, setGlyphIndex) => {
        console.log("update", side, "glyph with contentIndex :", contentIndex[side])
        if (font[side].orderedListOfGlyph[0] && validateSide(side)) {
            let val =   Object.keys(JSON.parse(font[side].orderedListOfContent[contentIndex[side]]))[0].toString();   // content
            let key = Object.values(JSON.parse(font[side].orderedListOfContent[contentIndex[side]]))[0].toString(); // glyph
            let obj = {[key]:[val][0]};
            let index = font[side].orderedListOfGlyph.indexOf(JSON.stringify(obj));
            //console.log("found on index", index)
            setGlyphIndex[side](index);
        } else {
            console.log("no orderedListOfContent yet")
        }
    }
    
    const updateContentIndex = (side, font, glyphIndex, setContentIndex) => {
        console.log("update", side, "content with glyphIndex :", glyphIndex[side])
        if (font[side].orderedListOfGlyph[0] && validateSide(side)) {
            let val =   Object.keys(JSON.parse(font[side].orderedListOfGlyph[glyphIndex[side]]))[0].toString();      // glyph
            let key = Object.values(JSON.parse(font[side].orderedListOfGlyph[glyphIndex[side]]))[0].toString();    // content
            let obj = {[key]:[val][0]};
            let index = font[side].orderedListOfContent.indexOf(JSON.stringify(obj));
            //console.log("found on index", index)
            setContentIndex[side](index);
        } else {
            console.log("no orderedListOfGlyph yet")
        }
    }
    
    
    useEffect(() => {
        console.log("Left glyphIndex :", glyphIndex.Left)
        updateContentIndex("Left", font, glyphIndex, setContentIndex)
    }, [glyphIndex.Left])
    
    useEffect(() => {
        console.log("Right glyphIndex :", glyphIndex.Right)
        updateContentIndex("Right", font, glyphIndex, setContentIndex)
    }, [glyphIndex.Right])
    
    useEffect(() => {
        console.log("Left contentIndex :", contentIndex.Left)
        updateGlyphIndex("Left", font, contentIndex, setGlyphIndex)
    }, [contentIndex.Left])
    
    useEffect(() => {
        console.log("Right contentIndex :", contentIndex.Right)
        updateGlyphIndex("Right", font, contentIndex, setGlyphIndex)
    }, [contentIndex.Right])
    
    
    async function onFontUpdate(side) {
        setUpdating(true);
        console.log("update",side,"side")
        
        let newData = new Object();
        
        if (side === "Left") {
            // get font 1 from file
            newData = {
                name: "icomoon-2",
                family: "Icomoon",
                content: ["e900",
                    "e902",
                    "e903",
                    "e904",
                    "e905",
                    "e906",
                    "e907",
                    "e908",
                    "e909",
                    "e90a",
                    "e90b",
                    "e90c",
                    "e90d",
                    "e90e",
                    "e90f",
                    "e910",
                    "e911",
                    "e912",
                    "e913",
                    "e914",
                    "e915",
                    "e916",
                    "e917",
                    "e918",
                    "e919",
                    "e91a",
                    "e91b",
                    "e91c",
                    "e91d",
                    "e91e",
                    "e91f",
                    "e920",
                    "e921",
                    "e922",
                    "e923",
                    "e924",
                    "e925",
                    "e926",
                    "e927",
                    "e928",
                    "e929",
                    "e92a",
                    "e92b",
                    "e92c",
                    "e92d",
                    "e934",
                    "e935",
                    "e936",
                    "e937",
                    "e938",
                    "e939",
                    "e93a",
                    "e93b",
                    "e93c",
                    "e93d",
                    "e93e",
                    "e93f",
                    "e940",
                    "e941",
                    "e945",
                    "e946",
                    "e947",
                    "e948",
                    "e949",
                    "e94a",
                    "e94b",
                    "e94c",
                    "e94d",
                    "e94e",
                    "e94f",
                    "e950",
                    "e951",
                    "e952",
                    "e953",
                    "e954",
                    "e955",
                    "e956",
                    "e957",
                    "e958",
                    "e959",
                    "e95a",
                    "e95b",
                    "e95c",
                    "e95d",
                    "e95e",
                    "e95f",
                    "e960",
                    "e961",
                    "e962",
                    "e963",
                    "e964",
                    "e965",
                    "e966",
                    "e967"],
                icoName: ['Picto-favoris',
                    'watch',
                    'toggleoff',
                    'toggleon',
                    'pricetags',
                    'hashtag',
                    'pricetag',
                    'cloudupload',
                    'qrcode',
                    'folder',
                    'briefcase',
                    'cut',
                    'chart',
                    'funnel',
                    'Page-1',
                    'playback',
                    'cloud',
                    'checkbox',
                    'callmade',
                    'phonering',
                    'callreceived',
                    'Phone-disabled',
                    'callcancel',
                    'Call-1',
                    'boxopen',
                    'cube',
                    'barchart',
                    'barchart2',
                    'barchart3',
                    'anchor',
                    'ellipse',
                    'add2',
                    'trashbin',
                    'trash',
                    'water',
                    'notificationoff',
                    'videocamoff',
                    'images',
                    'uploadimage',
                    'pinterest',
                    'reportimage',
                    'addimage',
                    'removeimage',
                    'removefile',
                    'lockfile',
                    'editfile',
                    'deletefile',
                    'addfile',
                    'searchbylocation',
                    'checkmark',
                    'close',
                    'add',
                    'Cloud-upload1',
                    'image',
                    'reportuser',
                    'communaute',
                    'businessman',
                    'unfriend',
                    'friendoffriend',
                    'loggingaspage',
                    'term',
                    'Stickers-1',
                    'setting',
                    'website',
                    'signal',
                    'confidentialite',
                    'photo',
                    'page',
                    'horaire',
                    'publier',
                    'public',
                    'Eye-close',
                    'eye',
                    'like',
                    'info',
                    'menu',
                    'call',
                    'group',
                    'tag (arobase)',
                    'addfriend',
                    'friend',
                    'home',
                    'edit',
                    'Stickers',
                    'message',
                    'share',
                    'notification',
                    'location',
                    'email',
                    'search',
                    'localisation',
                    'video',
                    'Menu-event',
                    'exit',
                ],
                classPrefix: ".icon-"
            };}
    
    
        if (side === "Right") {
            // get font 2 from file
            newData = {
                name: "lineficon",
                family: "Lineficon",
                content: [
                    'e915',
                    'e916',
                    'e917',
                    'e918',
                    'e919',
                    'e91a',
                    'e91b',
                    'e91c',
                    'e91d',
                    'e91e',
                    'e91f',
                    'e920',
                    'e921',
                    'e922',
                    'e923',
                    'e924',
                    'e925',
                    'e926',
                    'e927',
                    'e928',
                    'e929',
                    'e92a',
                    'e92b',
                    'e92c',
                    'e92d',
                    'e92e',
                    'e92f',
                    'e930',
                    'e931',
                    'e932',
                    'e933',
                    'e934',
                    'e935',
                    'e936',
                    'e937',
                    'e938',
                    'e939',
                    'e93a',
                    'e93b',
                    'e93c',
                    'e93d',
                    'e93e',
                    'e93f',
                    'e940',
                    'e941',
                    'e942',
                    'e943',
                    'e944',
                    'e945',
                    'e946',
                    'e947',
                    'e948',
                    'e949',
                    'e94a',
                    'e94b',
                    'e94c',
                    'e94d',
                    'e94e',
                    'e94f',
                    'e950',
                    'e951',
                    'e952',
                    'e953',
                    'e954',
                    'e955',
                    'e956',
                    'e957',
                    'e958',
                    'e959',
                    'e95a',
                    'e95b',
                    'e95c',
                    'e95d',
                    'e95e',
                    'e95f',
                    'e960',
                    'e961',
                    'e962',
                    'e963',
                    'e964',
                    'e965',
                    'e966',
                    'e967',
                    'e968',
                    'e969',
                    'e96a',
                    'e96b',
                    'e96c',
                    'e96d',
                    'e96e',
                    'e96f',
                    'e970',
                    'e971',
                    'e972',
                    'e973',
                    'e974',
                    'e975',
                    'e976',
                    'e977',
                    'e978',
                    'e979',
                    'e97a',
                    'e97b',
                    'e97c',
                    'e97d',
                    'e97e',
                    'e97f',
                    'e980',
                    'e981',
                    'e982',
                    'e983',
                    'e984',
                    'e985',
                    'e986',
                    'e987',
                    'e988',
                    'e989',
                    'e98a',
                    'e98b',
                    'e98c',
                    'e98d',
                    'e98e',
                    'e98f',
                    'e990',
                    'e991',
                    'e992',
                    'e993',
                    'e994',
                    'e995',
                    'e996',
                    'e997',
                    'e998',
                    'e999',
                    'e99a',
                    'e99b',
                    'e99c',
                    'e99d',
                    'e99e',
                    'e99f',
                    'e9a0',
                    'e9a1',
                    'e9a2',
                    'e9a3',
                    'e9a4',
                    'e9a5',
                    'e9a6',
                    'e9a7',
                    'e9a8',
                    'e9a9',
                    'e9aa',
                    'e9ab',
                    'e9ac',
                    'e9ad',
                    'e9ae',
                    'e9af',
                    'e9b0',
                    'e9b1',
                    'e9b2',
                    'e9b3',
                    'e9b4',
                    'e9b5',
                    'e9b6',
                    'e9b7',
                    'e9b8',
                    'e9b9',
                    'e9ba',
                    'e9bb',
                    'e9bc',
                    'e9bd',
                    'e9be',
                    'e9bf',
                    'e9c0',
                    'e9c1',
                    'e9c2',
                    'e9c3',
                    'e9c4',
                    'e9c5',
                    'e9c6',
                    'e9c7',
                    'e9c8',
                    'e9c9',
                    'e9ca',
                    'e9cb',
                    'e9cc',
                    'e9cd',
                    'e9ce',
                    'e9cf',
                    'e9d0',
                    'e9d1',
                    'e9d2',
                    'e9d3',
                    'e9d4',
                    'e9d5',
                    'e9d6',
                    'e9d7',
                    'e9d8',
                    'e9d9',
                    'e9da',
                    'e9db',
                    'e9dc',
                    'e9dd',
                    'e9de',
                    'e9df',
                    'e9e0',
                    'e9e1',
                    'e9e2',
                    'e9e3',
                    'e9e4',
                    'e9e5',
                    'e9e6',
                    'e9e7',
                    'e9e8',
                    'e9e9',
                    'e9ea',
                    'e9eb',
                    'e9ec',
                    'e9ed',
                    'e9ee',
                    'e9ef',
                    'e9f0',
                    'e9f1',
                    'e9f2',
                    'e9f3',
                    'e9f4',
                    'e9f5',
                    'e9f6',
                    'e9f7',
                    'e9f8',
                    'e9f9',
                    'e9fa',
                    'e9fb',
                    'e9fc',
                    'e9fd',
                    'e9fe',
                    'e9ff',
                    'ea00',
                    'ea01',
                    'ea02',
                    'ea03',
                    'ea04',
                    'ea05',
                    'ea06',
                    'ea07',
                    'ea08',
                    'ea09',
                    'ea0a',
                    'ea0b',
                    'ea0c',
                    'ea0d',
                    'ea0e',
                    'ea0f',
                    'ea10',
                    'ea11',
                    'ea12',
                    'ea13',
                    'ea14',
                    'ea15',
                    'ea16',
                    'ea17',
                    'ea18',
                    'ea19',
                    'ea1a',
                    'ea1b',
                    'ea1c',
                    'ea1d',
                    'ea1e',
                    'ea1f',
                    'ea20',
                    'ea21',
                    'ea22',
                    'ea23',
                    'ea24',
                    'ea25',
                    'ea26',
                    'ea27',
                    'ea28',
                    'ea29',
                    'ea2a',
                    'ea2b',
                    'ea2c',
                    'ea2d',
                    'ea2e',
                    'ea2f',
                    'ea30',
                    'ea31',
                    'ea32',
                    'ea33',
                    'ea34',
                    'ea35',
                    'ea36',
                    'ea37',
                    'ea38',
                    'ea39',
                    'ea3a',
                    'ea3b',
                    'ea3c',
                    'ea3d',
                    'ea3e',
                    'ea3f',
                    'ea40',
                    'ea41',
                    'ea42',
                    'ea43',
                    'ea44',
                    'ea45',
                    'ea46',
                    'ea47',
                    'ea48',
                    'ea49',
                    'ea4a',
                    'ea4b',
                    'ea4c',
                    'ea4d',
                    'ea4e',
                    'ea4f',
                    'ea50',
                    'ea51',
                    'ea52',
                    'ea53',
                    'ea54',
                    'ea55',
                    'ea56',
                    'ea57',
                    'ea58',
                    'ea59',
                    'ea5a',
                    'ea5b',
                    'ea5c',
                    'ea5d',
                    'ea5e',
                    'ea5f',
                    'ea60',
                    'ea61',
                    'ea62',
                    'ea63',
                    'ea64',
                    'ea65',
                    'ea66',
                    'ea67',
                    'ea68',
                    'ea69',
                    'ea6a',
                    'ea6b',
                    'ea6c',
                    'ea6d',
                    'ea6e',
                    'ea6f',
                    'ea70',
                    'ea71',
                    'ea72',
                    'ea73',
                    'ea74',
                    'ea75',
                    'ea76',
                    'ea77',
                    'ea78',
                    'ea79',
                    'ea7a',
                    'ea7b',
                    'ea7c',
                    'ea7d',
                    'ea7e',
                    'ea7f',
                    'ea80',
                    'ea81',
                    'ea82',
                    'ea83',
                    'ea84',
                    'ea85',
                    'ea86',
                    'ea87',
                    'ea88',
                    'ea89',
                    'ea8a',
                    'ea8b',
                    'ea8c',
                    'ea8d',
                    'ea8e',
                    'ea8f',
                    'ea90',
                    'ea91',
                    'ea92',
                    'ea93',
                    'ea94',
                    'ea95',
                    'ea96',
                    'ea97',
                    'ea98',
                    'ea99',
                    'ea9a',
                    'ea9b',
                    'ea9c',
                    'ea9d',
                    'ea9e',
                    'ea9f',
                    'eaa0',
                    'eaa1',
                    'eaa2',
                    'eaa3',
                    'eaa4',
                    'eaa5',
                    'eaa6',
                    'eaa7',
                    'eaa8',
                    'eaa9',
                    'eaaa',
                    'eaab',
                    'eaac',
                    'eaad',
                    'eaae',
                    'eaaf',
                    'eab0',
                    'eab1',
                    'eab2',
                    'eab3',
                    'eab4',
                    'eab5',
                    'eab6',
                    'eab7',
                    'eab8',
                    'eab9',
                    'eaba',
                    'eabb',
                    'eabc',
                    'eabd',
                    'eabe',
                    'eabf',
                    'eac0',
                    'eac1',
                    'eac2',
                    'eac3',
                    'eac4',
                    'eac5',
                    'eac6',
                    'eac7',
                    'eac8',
                    'eac9',
                    'eaca',
                    'eacb',
                    'eacc',
                    'eacd',
                    'eace',
                    'eacf',
                    'ead0',
                    'ead1',
                    'ead2',
                    'ead3',
                    'ead4',
                    'ead5',
                    'ead6',
                    'ead7',
                    'ead8',
                    'ead9',
                    'eada',
                    'eadb',
                    'eadc',
                    'eadd',
                    'eade',
                    'eadf',
                    'eae0',
                    'eae1',
                    'eae2',
                    'eae3',
                    'eae4',
                    'eae5',
                    'eae6',
                    'eae7',
                    'eae8',
                    'eae9',
                    'eaea',
                    'eaeb',
                    'eaec',
                    'eaed',
                    'eaee',
                    'eaef',
                    'eaf0',
                    'eaf1',
                    'eaf2',
                    'eaf3',
                    'eaf4',
                    'eaf5',
                    'eaf6',
                    'eaf7',
                    'eaf8',
                    'eaf9',
                    'eafa',
                    'eafb',
                    'eafc',
                    'eafd',
                    'eafe',
                    'eaff',
                    'eb00',
                    'eb01',
                    'eb02',
                    'eb03',
                    'eb04',
                    'eb05',
                    'eb06',
                    'eb07',
                    'eb08',
                    'eb09',
                    'eb0a',
                    'eb0b',
                    'eb0c',
                    'eb0d',
                    'eb0e',
                    'eb0f',
                    'eb10',
                    'eb11',
                    'eb12',
                    'eb13',
                    'eb14',
                    'eb15',
                    'eb16',
                    'eb17',
                    'eb18',
                    'eb19',
                    'eb1a',
                    'eb1b',
                    'eb1c',
                    'eb1d',
                    'eb1e',
                    'eb1f',
                    'eb20',
                    'eb21',
                    'eb22',
                    'eb23',
                    'eb24',
                    'eb25',
                    'eb26',
                    'eb27',
                    'eb28',
                    'eb29',
                    'eb2a',
                    'eb2b',
                    'eb2c',
                    'eb2d',
                    'eb2e',
                    'eb2f',
                    'eb30',
                    'eb31',
                    'eb32',
                    'eb33',
                    'eb34',
                    'eb35',
                    'eb36',
                    'eb37',
                    'eb38',
                    'eb39',
                    'eb3a',
                    'eb3b',
                    'eb3c',
                    'eb3d',
                    'eb3e',
                    'eb3f',
                    'eb40',
                    'eb41',
                    'eb42',
                    'eb43',
                    'eb44',
                    'eb45',
                    'eb46',
                    'eb47',
                    'eb48',
                    'eb49',
                    'eb4a',
                    'eb4b',
                    'eb4c',
                    'eb4d',
                    'eb4e',
                    'eb4f',
                    'eb50',
                    'eb51',
                    'eb52',
                    'eb53',
                    'eb54',
                    'eb55',
                    'eb56',
                    'eb57',
                    'eb58',
                    'eb59',
                    'eb5a',
                    'eb5b',
                    'eb5c',
                    'eb5d',
                    'eb5e',
                    'eb5f',
                    'eb60',
                    'eb61',
                    'eb62',
                    'eb63',
                    'eb64',
                    'eb65',
                    'eb66',
                    'eb67',
                    'eb68',
                    'eb69',
                    'eb6a',
                    'eb6b',
                    'eb6c',
                    'eb6d',
                    'eb6e',
                    'eb6f',
                    'eb70',
                    'eb71',
                    'eb72',
                    'eb73',
                    'eb74',
                    'eb75',
                    'eb76',
                    'eb77',
                    'eb78',
                    'eb79',
                    'eb7a',
                    'eb7b',
                    'eb7c',
                    'eb7d',
                    'eb7e',
                    'eb7f',
                    'eb80',
                    'eb81',
                    'eb82',
                    'eb83',
                    'eb84',
                    'eb85',
                    'eb86',
                    'eb87',
                    'eb88',
                    'eb89',
                    'eb8a',
                    'eb8b',
                    'eb8c',
                    'eb8d',
                    'eb8e',
                    'eb8f',
                    'eb90',
                    'eb91',
                    'eb92',
                    'eb93',
                    'eb94',
                    'eb95',
                    'eb96',
                    'eb97',
                    'eb98',
                    'eb99',
                    'eb9a',
                    'eb9b',
                    'eb9c',
                    'eb9d',
                    'eb9e',
                    'eb9f',
                    'eba0',
                    'eba1',
                    'eba2',
                    'eba3',
                    'eba4',
                    'eba5',
                    'eba6',
                    'eba7',
                    'eba8',
                    'eba9',
                    'ebaa',
                    'ebab',
                    'ebac',
                    'ebad',
                    'ebae',
                    'ebaf',
                    'ebb0',
                    'ebb1',
                    'ebb2',
                    'ebb3',
                    'ebb4',
                    'ebb5',
                    'ebb6',
                    'ebb7',
                    'ebb8',
                    'ebb9',
                    'ebba',
                    'ebbb',
                    'ebbc',
                    'ebbd',
                    'ebbe',
                    'ebbf',
                    'ebc0',
                    'ebc1',
                    'ebc2',
                    'ebc3',
                    'ebc4',
                    'ebc5',
                    'ebc6',
                    'ebc7',
                    'ebc8',
                    'ebc9',
                    'ebca',
                    'ebcb',
                    'ebcc',
                    'ebcd',
                    'ebce',
                    'ebcf',
                    'ebd0',
                    'ebd1',
                    'ebd2',
                    'ebd3',
                    'ebd4',
                    'ebd5',
                    'ebd6',
                    'ebd7',
                    'ebd8',
                    'ebd9',
                    'ebda',
                    'ebdb',
                    'ebdc',
                    'ebdd',
                    'ebde',
                    'ebdf',
                    'ebe0',
                    'ebe1',
                    'ebe2',
                    'ebe3',
                    'ebe4',
                    'ebe5',
                    'ebe6',
                    'ebe7',
                    'ebe8',
                    'ebe9',
                    'ebea',
                    'ebeb',
                    'ebec',
                    'ebed',
                    'ebee',
                    'ebef',
                    'ebf0',
                    'ebf1',
                    'ebf2',
                    'ebf3',
                    'ebf4',
                    'ebf5',
                    'ebf6',
                    'ebf7',
                    'ebf8',
                    'ebf9',
                    'ebfa',
                    'ebfb',
                    'ebfc',
                    'ebfd',
                    'ebfe',
                    'ebff',
                    'ec00',
                    'ec01',
                    'ec02',
                    'ec03',
                    'ec04',
                    'ec05',
                    'ec06',
                    'ec07',
                    'ec08',
                    'ec09',
                    'ec0a',
                    'ec0b',
                    'ec0c',
                    'ec0d',
                    'ec0e',
                    'ec0f',
                    'ec10',
                    'ec11',
                    'ec12',
                    'ec13',
                    'ec14',
                    'ec15',
                    'ec16',
                    'ec17',
                    'ec18',
                    'ec19',
                    'ec1a',
                    'ec1b',
                    'ec1c',
                    'ec1d',
                    'ec1e',
                    'ec1f',
                    'ec20',
                    'ec21',
                    'ec22',
                    'ec23',
                    'ec24',
                    'ec25',
                    'ec26',
                    'ec27',
                    'ec28',
                    'ec29',
                    'ec2a',
                    'ec2b',
                    'ec2c',
                    'ec2d',
                    'e900',
                    'e901',
                    'e902',
                    'e903',
                    'e904',
                    'e905',
                    'e906',
                    'e907',
                    'e908',
                    'e909',
                    'e90a',
                    'e90b',
                    'e90c',
                    'e90d',
                    'e90e',
                    'e90f',
                    'e910',
                    'e911',
                    'e912',
                    'e913',
                    'e914',
                ],
                icoName: [
                    'barchart-increase-o',
                    'box-o',
                    'comment-square-o',
                    'trash-alt-o',
                    'trash-empty-alt-o',
                    'video-off',
                    'bell2-off-o',
                    'money-bag-o',
                    'money-bag',
                    'bell2-o',
                    'droplet-o',
                    'external-link',
                    'barchart-increase-alt',
                    'fast-forward',
                    'filter',
                    'phone-forwarded',
                    'phone-incoming2',
                    'phone-missed',
                    'phone-off',
                    'phone-outgoing2',
                    'rewind',
                    'briefcase-o',
                    'chart-pie-o:b',
                    'video',
                    'check-square-alt',
                    'cloud-alt-o',
                    'folder-o',
                    'phone-call',
                    'phone-o',
                    'scissors',
                    'flip-v',
                    'flip-h',
                    'toggle-left-o',
                    'toggle-right-o',
                    'upload-cloud',
                    'watch-o',
                    'hashtag',
                    'price-tag',
                    'price-tags',
                    'qrcode',
                    'dollar-circle-o',
                    'dollar-circle',
                    'coin-pound',
                    'euro-circle',
                    'credit-card-o',
                    'creditcard',
                    'telephone',
                    'address-book',
                    'address-book-o',
                    'eye-off-o',
                    'eye-off',
                    'question-mark',
                    'cubes-o',
                    'help-alt-o',
                    'help-alt',
                    'newspaper-o',
                    'newspaper',
                    'layers-o',
                    'businessman',
                    'businessman-del',
                    'businessman-plus',
                    'businessman-clock',
                    'businessman-group',
                    'layers',
                    'graduation-cap-o',
                    'radio',
                    'sun-alt-o2',
                    'compass-o',
                    'compass',
                    'inbox-o',
                    'inbox',
                    'inbox-full-o',
                    'inbox-full',
                    'medal-o',
                    'medal',
                    'store-alt',
                    'pen',
                    'camera-off-o',
                    'link-break',
                    'thumbdown-alt-o',
                    'thumbup-alt-o',
                    'arrows-move',
                    'graduation-cap-alt',
                    'goleft',
                    'alarm-o-alt',
                    'goright',
                    'gear-alt-o',
                    'star-circle-o',
                    'star-circle',
                    'check-circle-alt',
                    'bell-alt-o',
                    'bell-alt',
                    'comment-dots-o',
                    'comment-dots',
                    'comment-chart-o',
                    'comment-chart',
                    'comment-check-o',
                    'comment-check',
                    'quotes-left',
                    'quotes-right',
                    'globe-alt-o',
                    'gplus-circle',
                    'comment-square-del-o',
                    'paint-brush-o',
                    'facebook-circle',
                    'paint-brush',
                    'paperplane',
                    'pinterest-circle',
                    'thumbdown-alt',
                    'thumbup-alt',
                    'twitter',
                    'twitter-circle-o',
                    'twitter-circle',
                    'facebook',
                    'facebook-square',
                    'user2-two-o',
                    'user1-two-o',
                    'user1-three-o',
                    'gplus',
                    'droplet',
                    'gplus-circle-o',
                    'facebook-circle-o',
                    'circle',
                    'circle-inside-o',
                    'square-o',
                    'square',
                    'square-inside-o',
                    'gear-alt',
                    'file-code',
                    'snowflake',
                    'chart-pie',
                    'briefcase',
                    'folder',
                    'folder-check-o',
                    'stats-dots',
                    'barchart-decrease-alt',
                    'folder-check',
                    'folder-plus-o',
                    'folder-plus',
                    'folder-minus-o',
                    'folder-minus',
                    'folder-del-o',
                    'folder-del',
                    'music-note',
                    'music-list',
                    'disc-alt',
                    'disc-alt-o',
                    'music-album',
                    'music-list-o',
                    'film-circle',
                    'film-alt',
                    'volume-o',
                    'volume-del-o',
                    'volume-plus-o',
                    'volume-minus-o',
                    'movie',
                    'folder-star-o',
                    'folder-star',
                    'toggle-left',
                    'toggle-right',
                    'power',
                    'upload-off',
                    'download-off',
                    'download-alt',
                    'sound-wave',
                    'download-off-alt',
                    'trash-alt',
                    'user1-two',
                    'user1-three',
                    'comment-square-empty-o',
                    'comment-square-empty',
                    'comment-square',
                    'comment-square-del',
                    'comment-empty-o',
                    'comment-empty',
                    'comment-plus-o',
                    'comment-plus',
                    'comment-del-o',
                    'comment-del',
                    'watch',
                    'bluetooth',
                    'warning-circle',
                    'warning-circle-o',
                    'signin',
                    'signout',
                    'eye-alt',
                    'eye-alt-plus',
                    'eye-alt-minus',
                    'eye-alt-blocked',
                    'linkedin',
                    'linkedin-circle-o',
                    'user2-star-o',
                    'linkedin-circle',
                    'contrast',
                    'linkedin-square-o',
                    'linkedin-square',
                    'facebook-square-o',
                    'bluetooth-alt',
                    'bluetooth-alt-o',
                    'bus',
                    'sandclock-empty-o',
                    'sandclock-start-o',
                    'sandclock-end-o',
                    'magic',
                    'sandclock-goingon-o',
                    'car-taxi',
                    'sandclock-exprired-o',
                    'sandclock-exprired-alt-o',
                    'comment-minus-o',
                    'comment-minus',
                    'file-code-o',
                    'file-pdf-o',
                    'file-photo-o',
                    'photos-del',
                    'file-powerpoint-o',
                    'photos-down',
                    'file-sound-o',
                    'photos-minus',
                    'file-text-o',
                    'photos-plus',
                    'file-word-o',
                    'file-zip-o',
                    'hourglass-end',
                    'hourglass-start',
                    'language',
                    'file-excel-o',
                    'key',
                    'key-o',
                    'key-alt',
                    'text-file-upload',
                    'text-file-search',
                    'key-alt-o',
                    'mouse',
                    'file-movie-o',
                    'hammer',
                    'graduation-cap',
                    'music-note-o',
                    'photo',
                    'photo-plus-o',
                    'photo-minus-o',
                    'photo-warning-o',
                    'photo-del-o',
                    'photo-del',
                    'photo-up-o',
                    'photo-down-o',
                    'photo-down',
                    'rss-o',
                    'info-circle-alt-o',
                    'info-circle-alt',
                    'photo-lock-o',
                    'photo-lock',
                    'photo-question-o',
                    'photo-question',
                    'rss',
                    'rss-square',
                    'photo-star-o',
                    'photo-star',
                    'text-file-download',
                    'photo-check-o',
                    'photo-check',
                    'businesswoman',
                    'save-o',
                    'save',
                    'photo-heart-o',
                    'wifi',
                    'sex-unknown',
                    'photo-heart',
                    'photo-ban-o',
                    'photo-ban',
                    'photos-o',
                    'photos-alt-o',
                    'photos-alt',
                    'photos-plus-o',
                    'photos-minus-o',
                    'fire',
                    'photos-warning-o',
                    'photos-warning',
                    'photos-del-o',
                    'photos-up-o',
                    'photos-up',
                    'photos-down-o',
                    'refresh-o',
                    'help2',
                    'lightbulb-alt',
                    'ticket-o',
                    'ticket',
                    'photos-lock-o',
                    'photos-lock',
                    'photos-question-o',
                    'photos-question',
                    'file-empty-o',
                    'camera-off',
                    'photos-star-o',
                    'tvplay',
                    'photos-star',
                    'giftbox',
                    'photos-check-o',
                    'photos-check',
                    'photos-ban-o',
                    'photos-ban',
                    'pinterest',
                    'car',
                    'flag-triangle',
                    'box',
                    'angle-double-up',
                    'format-paint',
                    'move-up',
                    'move-down',
                    'angle-double-down',
                    'angle-double-left',
                    'flag-triangle-o',
                    'flag-alt',
                    'flag-alt-o',
                    'flag-rectangle',
                    'flag-rectangle-o',
                    'loading-icon',
                    'angle-double-right',
                    'color-palette',
                    'plus-circle-o',
                    'mouse-alt',
                    'paperplane-left',
                    'calendar',
                    'plus-circle',
                    'minus-circle-o',
                    'minus-circle',
                    'active-dir',
                    'star-plus-o',
                    'birthday-cake-alt',
                    'star-plus',
                    'merge-file-o',
                    'birthday-cake',
                    'merge-file',
                    'thumb-tack-o',
                    'folder-alt-o',
                    'folder-alt',
                    'spoon-knife',
                    'play-repeat-one-o',
                    'play-repeat-one',
                    'play-repeat-o',
                    'play-repeat',
                    'paperclip-alt',
                    'paperclip',
                    'rotate-left',
                    'thumb-tack',
                    'rotate-right',
                    'businessman-question',
                    'businessman-sent',
                    'businessman-check',
                    'crown-o',
                    'crown',
                    'globe',
                    'calendar-plus',
                    'comment-o',
                    'comments',
                    'bell',
                    'bell-o',
                    'diamond',
                    'diamond-o',
                    'check-square-o',
                    'checkin-o',
                    'checkin',
                    'calendar-check-o',
                    'calendar-check',
                    'calendar-o',
                    'dottedmore-o',
                    'dottedmore-vertical-o',
                    'close-circle-o',
                    'close-circle',
                    'controlboard-o',
                    'controlboard',
                    'gear-o',
                    'gear',
                    'search-o',
                    'search-minus-o',
                    'search-user-o',
                    'search-user',
                    'search-minus',
                    'search-plus',
                    'arrow-left',
                    'calendar-del-o',
                    'calendar-del',
                    'calendar-plus-o',
                    'calendar-star-o',
                    'calendar-star',
                    'bookmark-o',
                    'bookmark',
                    'dottedmore-vertical',
                    'search',
                    'camera-o',
                    'camera',
                    'clock-o',
                    'clock',
                    'thumbup',
                    'thumbup-o',
                    'thumbdown-o',
                    'thumbdown',
                    'godown',
                    'heart-o',
                    'heart',
                    'goup',
                    'home',
                    'headphone',
                    'headphone-o',
                    'user-man-o',
                    'user-man',
                    'compose-alt',
                    'compose',
                    'cart-o',
                    'cart',
                    'plus',
                    'minus',
                    'star-o',
                    'star',
                    'close',
                    'check-circle-o',
                    'check-circle',
                    'angle-left',
                    'angle-down',
                    'angle-up',
                    'angle-right',
                    'comment',
                    'lightbub-o',
                    'lightbub',
                    'user1-text-o',
                    'gplus-alt',
                    'copy-o',
                    'copy',
                    'forward-o',
                    'newspaper-alt',
                    'lightbulb-alt2',
                    'gift-o',
                    'gift',
                    'link',
                    'lock-o',
                    'lock',
                    'dottedmore',
                    'paperplane-alt-o',
                    'rocket',
                    'gplus-circle-alt-o',
                    'pencilline',
                    'pencilline-o',
                    'gplus-circle-alt',
                    'pencil',
                    'rotate-left-alt',
                    'reshare',
                    'printer-o',
                    'printer',
                    'share-o',
                    'share',
                    'play-circle-o',
                    'play-circle',
                    'shield',
                    'shield-o',
                    'smile-o',
                    'smile',
                    'sponsor',
                    'shopbasket',
                    'shopbasket-o',
                    'shuffle',
                    'unlock',
                    'trophy-o',
                    'trophy',
                    'store-o',
                    'videocam-o',
                    'desktop-linechart-o',
                    'desktop-linechart',
                    'voice-o',
                    'voice',
                    'user1-plus',
                    'caret-up',
                    'caret-down',
                    'paragraph-minus',
                    'paragraph-plus',
                    'list-up',
                    'list-down',
                    'user-couple-o',
                    'user-couple',
                    'user-man-plus-o',
                    'user-man-plus',
                    'user1',
                    'user1-o',
                    'user-man-three',
                    'shutdown',
                    'arrow-right',
                    'arrow-up',
                    'arrow-down',
                    'mobile',
                    'target-o',
                    'compass-cirlce',
                    'compass-circle-o',
                    'dics',
                    'disc-o',
                    'stop-circle',
                    'stop-circle-o',
                    'ban',
                    'arrows',
                    'map-o',
                    'map',
                    'envelope-o',
                    'envelope',
                    'pause',
                    'pause-o',
                    'sun-minus',
                    'sun',
                    'sun-o',
                    'unlock-o',
                    'alignleft',
                    'alignright',
                    'info-circle-o',
                    'info-circle',
                    'forward',
                    'reply-o',
                    'reply',
                    'envelope-opened-o',
                    'check',
                    'trash',
                    'trash-o',
                    'flag-waving-o',
                    'desktop-o',
                    'th-large',
                    'th-large-o',
                    'warning-o',
                    'warning',
                    'th-o',
                    'alarm-o',
                    'alarm',
                    'rotate-right-alt',
                    'question-circle',
                    'question-circle-o',
                    'heart-circle-o',
                    'star-half-o',
                    'check-square',
                    'play-o',
                    'play',
                    'eye-o',
                    'eye',
                    'caret-right',
                    'caret-left',
                    'play-next-o',
                    'play-next',
                    'sun-plus-o',
                    'sun-minus-o',
                    'download',
                    'upload',
                    'home-o-alt',
                    'home-alt',
                    'file',
                    'play-prev-o',
                    'play-prev',
                    'comments-o',
                    'th',
                    'heart-circle',
                    'videocam',
                    'pause-circle',
                    'pause-circle-o',
                    'instagram-o',
                    'mobile-o',
                    'upload-alt',
                    'upload-off-alt',
                    'user-circle',
                    'user-circle-o',
                    'sun-plus',
                    'user-man-three-o',
                    'textedit',
                    'user1-plus-o',
                    'user2-clock-o',
                    'user2-question-o',
                    'user2-comment-o',
                    'user2-up-o',
                    'user2-check-o',
                    'user2-down-o',
                    'user2-prev-o',
                    'user2-next-o',
                    'user2-del-o',
                    'user2-minus-o',
                    'user2-plus-o',
                    'user2-text-o',
                    'user2-edit-o',
                    'user2-heart-o',
                    'user3-two',
                    'search-plus-o',
                    'flag-waving',
                    'user2-three-o',
                    'globe-o',
                    'navbar',
                    'aligncenter',
                    'instagram',
                    'whatsapp-o',
                    'whatsapp',
                    'repeat-alt',
                    'file-text',
                    'youtube',
                    'youtube-logo',
                    'twitch',
                    'vimeo',
                    'vimeo2',
                    'dribbble',
                    'behance',
                    'appleinc',
                    'android',
                    'skype',
                    'chrome',
                    'firefox',
                    'IE',
                    'file-rss-o',
                    'file-rss',
                    'file-photo',
                    'file-word',
                    'file-powerpoint',
                    'file-sound',
                    'file-movie',
                    'file-excel',
                    'folders-o',
                    'folders',
                    'folders-edit-o',
                    'folders-config-o',
                    'cart-checkout-o',
                    'cart-full-o',
                    'cart-del-o',
                    'cart-minus-o',
                    'cart-plus-o',
                    'cart-plus',
                    'cart-minus',
                    'cart-del',
                    'rocket-o',
                    'comment-hashtag-o',
                    'comment-hashtag',
                    'truck',
                    'list-o',
                    'list',
                    'rss-square-o',
                    'activedir-o',
                    'casual-o',
                    'casual',
                    'user-circle-alt-o',
                    'alarm-alt',
                    'user1-clock-o',
                    'user1-clock',
                    'user1-minus-o',
                    'user1-minus',
                    'user1-check-o',
                    'user1-check',
                    'arrow-collapse',
                    'arrow-expand',
                    'sticker-o',
                    'sticker',
                    'quote-alt-left',
                    'quote-alt-right',
                    'quote-circle-alt-left-o',
                    'quote-circle-alt-left',
                    'reply-alt',
                    'reply-all-alt',
                    'comments-square',
                    'comment-quote-o',
                    'comment-quote',
                    'bell2',
                    'list-sort',
                    'share-alt-o',
                    'share-alt',
                    'controlboard-h-o',
                    'controlboard-h',
                    'photo-frames-o',
                    'cup-o',
                    'cup',
                    'code',
                    'undo',
                    'redo',
                    'cup-straw-o',
                    'cup-straw',
                    'hat-o',
                    'hat',
                    'speed-watch-o',
                    'speed-watch',
                    'speed-watch-alt-o',
                    'speed-watch-alt',
                    'wallet-o',
                    'wallet',
                    'file-text-alt',
                    'file-pdf',
                    'price-tag-o',
                    'barchart',
                    'barchart-circle-o',
                    'barchart-circle',
                    'barchart-increase',
                    'barchart-decrease-o',
                    'barchart-decrease',
                    'volume',
                    'volume-decrease-o',
                    'volume-decrease',
                    'volume-increase-o',
                    'volume-increase',
                    'volume-del',
                    'volume-plus',
                    'volume-minus',
                    'user-woman-o',
                    'user-woman',
                    'user-woman-plus-o',
                    'user-woman-plus',
                    'user-woman-minus-o',
                    'user-woman-minus',
                    'user-two-women-o',
                    'user-two-women',
                    'user-man-minus-o',
                    'user-man-minus',
                    'user-two-men-o',
                    'user-two-men',
                    'user3-o',
                    'user3',
                    'user3-plus-o',
                    'user3-plus',
                    'user3-minus-o',
                    'user3-plus2',
                    'user3-check-o',
                    'user3-check',
                    'user3-del-o',
                    'user3-del',
                    'user3-text-o',
                    'user3-text',
                    'user3-next-o',
                    'user3-next',
                    'user3-up-o',
                    'user3-up',
                    'user3-clock-o',
                    'user3-clock',
                    'user3-two-o',
                    'user3-two2',
                    'user3-three',
                    'list-plus',
                    'list-del',
                    'camera-square-o',
                    'camera-square',
                    'lock-circle-o',
                    'lock-circle',
                    'unlock-circle-o',
                    'unlock-circle-o2',
                    'arrow-left-circle-o',
                    'arrow-left-circle',
                    'arrow-right-circle-o',
                    'arrow-right-circle',
                    'arrow-up-circle-o',
                    'arrow-up-circle',
                    'arrow-up-circle-o2',
                    'arrow-down-circle',
                    'check-square-o2',
                    'check-square-o3',
                    'bell2-off',
                    'comment-square-plus-o',
                    'comment-square-plus',
                    'comment-square-dots-o',
                    'comment-square-dots',
                    'video-player-o',
                    'video-player',
                    'list-bullet-o',
                    'cloud-alt',
                    'list-bullet',
                    'cloud-o',
                    'cloud',
                    'cloud-down-o',
                    'cloud-up-o',
                    'cloud-down-alt-o',
                    'newspaper-alt-o',
                    'photo-moveup-o',
                    'photo-moveup',
                    'photo-movedown-o',
                    'photo-movedown',
                    'desktop-text-o',
                    'desktop-text',
                    'gift-o2',
                    'gift-o3',
                    'comment-square-quote-o',
                    'comment-square-quote',
                    'comment-square-chart-o',
                    'comment-square-chart',
                    'comment-square-check-o',
                    'comment-square-check',
                    'comment-square-play-o',
                    'comment-square-play',
                    'comment-square-hashtag-o',
                    'comment-square-hashtag',
                    'comment-square-smile-o',
                    'comment-square-smile',
                    'comment-play-o',
                    'comment-play',
                    'comment-smile-o',
                    'comment-smile',
                    'stats-bars',
                    'bar-chart-2',
                    'bar-chart2',
                    'bar-chart',
                    'note-paper-o',
                    'note-paper',
                    'gear-form-o',
                    'gear-form',
                    'photo-o',
                    'photo-plus',
                    'photo-minus',
                    'photo-warning',
                    'photo-up',
                    'pinterest-circle-o',
                    'circle-o',
                    'photos',
                    'file-text-alt-o',
                    'text-file-lock',
                    'text-file-edit',
                    'text-file-plus',
                    'text-file-minus',
                    'text-file-del',
                    'dropbox',
                    'user1-text',
                    'user1-del-o',
                    'user1-del',
                    'anchor',
                    'at-sign',
                    'barchart-o',
                ],
                classPrefix: ".ico-"
            };}
        
        // generate lists
        let listOfContent = [];
        let listOfGlyph = [];
        
        await (function()  {
            for (let i=0; i < newData.content.length; i++) {
                listOfContent.push(JSON.stringify({[newData.content[i]]:newData.icoName[i]}))
                listOfGlyph.push(JSON.stringify({[newData.icoName[i]]:newData.content[i]}))
            }
        })();

        // aggregate ordered lists
        await (function()  {
            newData.orderedListOfContent = listOfContent.sort(compOrder).map(c => c);
            newData.orderedListOfGlyph = listOfGlyph.sort(compOrder).map(g => g);
        })();
        

        // set font
        //console.log(newData)
        setter[side](newData);
    
        await (function()  {
            updateGlyphIndex("Left", font, {Left: 0, Right: 0}, setGlyphIndex)
            updateGlyphIndex("Right", font, {Left: 0, Right: 0}, setGlyphIndex)
        })();
    
        // jobs done
        setUpdating(false);
        
    }
    
    
    function compOrder(obj1,obj2) {
        let a = Object.keys(JSON.parse(obj1))[0].toString().toLowerCase();
        let b = Object.keys(JSON.parse(obj2))[0].toString().toLowerCase();
        
        if (a===b) {return 0}
        
        for (let i=0; i < Math.min(a.length, b.length); i++) {
            if (a.charCodeAt(i) < b.charCodeAt(i)) { return -1 }
            if (a.charCodeAt(i) > b.charCodeAt(i)) { return 1 }
        }
    }
    
    
    const style = {
        leftPanel: "ml-[8vw] mr-[auto]",
        rightPanel: "ml-[auto] mr-[8vw]",
        block: "border border-1 sm:border-2 flex flex-row",
        ico: "h-[12vw] w-[12vw] border border-1 sm:border-2 flex justify-center items-center",
        content: "h-[12vw] w-[20vw] border border-1 sm:border-2 flex justify-center items-center",
        name: "h-[4vw] w-[32vw] border border-1 sm:border-2 flex items-center pl-[2vw]",
        center: "flex justify-center items-center flex-1",
        btn: "h-[8vw] w-[8vw] border border-1 sm:border-2 flex justify-center items-center"
    }
    
    
    
    return (
        <>
            <div className={"flex flex-row flex-wrap justify-between"}>
                <FileSelector side={"Left"} style={style}
                              font={font} setter={setter}
                              file={file} setFile={setFile}
                              updating={updating} onFontUpdate={onFontUpdate}/>
                
                <div className={`${style.rightPanel} ${style.center}`}>
                    {/*<p onClick={() => !updating && onFontUpdate("Right")}>*/}
                    {/*    {font.Right.name || "select css file"}*/}
                    {/*</p>*/}
                    <div>
                        {/*<span>Right font</span>*/}
                        <label htmlFor="rightsidefile" className={"text-[2vw]"}>
                            <input type="file" id="rightsidefile" name="rightsidefile"
                                   className={"file:w-[3vw] file:text-transparent"}
                                   onInput={() => !updating && onFontUpdate("Right")}
                            />
                        </label>
                    </div>
                </div>
            </div>
    
    
            <div className={"flex flex-row flex-wrap justify-between"}>
                {font.Left.orderedListOfContent[0] &&
                <HalfLine side={"Left"} style={style} font={font} cmd={cmd} setCmd={setCmd} contentIndex={contentIndex}
                    glyphIndex={glyphIndex} setContentIndex={setContentIndex} setGlyphIndex={setGlyphIndex} setter={setter}
                    updateGlyphIndex={updateGlyphIndex} updateContentIndex={updateContentIndex}
                />
                }
        
                {font.Right.orderedListOfContent[0] &&
                <HalfLine side={"Right"} style={style} font={font} cmd={cmd} setCmd={setCmd} contentIndex={contentIndex}
                    glyphIndex={glyphIndex} setContentIndex={setContentIndex} setGlyphIndex={setGlyphIndex} setter={setter}
                    updateGlyphIndex={updateGlyphIndex} updateContentIndex={updateContentIndex}
                />
                }
            </div>
            
        </>
    )
}

// OLD version


{/*            <div className={"flex flex-row flex-wrap justify-between none"}>
                {font.Left.orderedListOfContent[0] &&
                <div className={style.leftPanel}>
                    <div id={"left-side"} className={style.block}>
                        <UpDown side={"Left"}
                                index={cmd.Left === "content" ? contentIndex.Left : glyphIndex.Left}
                                setIndex={cmd.Left === "content" ? setContentIndex.Left : setGlyphIndex.Left}
                                max={font.Left.orderedListOfContent.length - 1}
                                onClick={() => {
                                    //cmd.Left === "content" ? updateGlyphIndex("Left", font, contentIndex, setGlyphIndex) : updateContentIndex("Left", font, glyphIndex, setContentIndex)
                                }}
                                onWheel={(e) => {
                                    let index = cmd.Left === "content" ? contentIndex.Left : glyphIndex.Left;
                                    let setIndex = cmd.Left === "content" ? setContentIndex.Left : setGlyphIndex.Left;
                                    let max = font.Left.orderedListOfContent.length - 1;
                                    cmd.Left === "content" ?
                                        handleWheel(e, "Left", index, max, setIndex, () => updateGlyphIndex("Left", font, contentIndex, setGlyphIndex)) :
                                        handleWheel(e, "Left", index, max, setIndex, () => updateContentIndex("Left", font, glyphIndex, setContentIndex))
                                }}
                        />
                        <div>
                            <div className={"flex flex-row"}>
                                <div className={style.content}
                                     onClick={() => {
                                         if (cmd.Left !== "content") {
                                             console.log("content on left")
                                             setCmd.Left("content");
                                             //updateGlyphIndex("Left", font, contentIndex, setGlyphIndex);
                                         }
                                     }}
                                >
                                <span>{font.Left.orderedListOfContent[0] && (
                                    cmd.Left === "content" && Object.keys(JSON.parse(font.Left.orderedListOfContent[contentIndex.Left]))[0] ||
                                    cmd.Left === "glyph" && Object.values(JSON.parse(font.Left.orderedListOfGlyph[glyphIndex.Left]))[0]
                                )}</span>
                                </div>
                                <div className={style.ico}>
                                    {font.Left.orderedListOfContent[0] &&
                                    <span className={`ico_${Object.keys(JSON.parse(font.Left.orderedListOfContent[contentIndex.Left]))[0]} font-left text-8xl`}/>
                                    }
                                </div>
                            </div>
                            <div className={style.name}
                                 onClick={() => {
                                     if (cmd.Left !== "glyph") {
                                         console.log("glyph on left")
                                         setCmd.Left("glyph");
                                         //updateContentIndex("Left", font, glyphIndex, setContentIndex);
                                     }
                                 }}
                            >
                            <span>{font.Left.orderedListOfGlyph[0] && (
                                cmd.Left === "content" && Object.values(JSON.parse(font.Left.orderedListOfContent[contentIndex.Left]))[0] ||
                                cmd.Left === "glyph" && Object.keys(JSON.parse(font.Left.orderedListOfGlyph[glyphIndex.Left]))[0]
                            )}</span>
                            </div>
                        </div>
                    </div>
                </div> }
        
                {font.Right.orderedListOfContent[0] &&
                <div className={style.rightPanel}>
                    <div id={"right-side"} className={style.block}>
                        <div>
                            <div className={"flex flex-row"}>
                                <div className={style.ico}>
                                    {font.Right.orderedListOfContent[0] &&
                                    <span className={`ico_${Object.keys(JSON.parse(font.Right.orderedListOfContent[contentIndex.Right]))[0]} font-right text-8xl`}/>
                                    }
                                </div>
                                <div className={style.content}
                                     onClick={() => {
                                         if (cmd.Right !== "content") {
                                             console.log("content on right")
                                             setCmd.Right("content");
                                             //updateGlyphIndex("Right", font, contentIndex, setGlyphIndex);
                                         }
                                     }}
                        
                                >
                                <span>{font.Right.orderedListOfContent[0] && (
                                    cmd.Right === "content" && Object.keys(JSON.parse(font.Right.orderedListOfContent[contentIndex.Right]))[0] ||
                                    cmd.Right === "glyph" && Object.values(JSON.parse(font.Right.orderedListOfGlyph[glyphIndex.Right]))[0]
                                )}</span>
                                </div>
                            </div>
                            <div className={style.name}
                                 onClick={() => {
                                     if (cmd.Right !== "glyph") {
                                         console.log("glyph on right")
                                         setCmd.Right("glyph");
                                         //updateContentIndex("Left", font, glyphIndex, setContentIndex);
                                     }
                                 }}
                            >
                            <span>{font.Right.orderedListOfGlyph[0] && (
                                cmd.Right === "content" && Object.values(JSON.parse(font.Right.orderedListOfContent[contentIndex.Right]))[0] ||
                                cmd.Right === "glyph" && Object.keys(JSON.parse(font.Right.orderedListOfGlyph[glyphIndex.Right]))[0]
                            )}</span>
                            </div>
                        </div>
                        <UpDown side={"Right"}
                                index={cmd.Right === "content" ? contentIndex.Right : glyphIndex.Right}
                                setIndex={cmd.Right === "content" ? setContentIndex.Right : setGlyphIndex.Right}
                                max={font.Right.orderedListOfContent.length - 1}
                                onClick={() => {
                                    //cmd.Right === "content" ? updateGlyphIndex("Right", font, contentIndex, setGlyphIndex) : updateContentIndex("Right", font, glyphIndex, setContentIndex)
                                }}
                                onWheel={(e) => {
                                    let index = cmd.Right === "content" ? contentIndex.Right : glyphIndex.Right;
                                    let setIndex = cmd.Right === "content" ? setContentIndex.Right : setGlyphIndex.Right;
                                    let max = font.Right.orderedListOfContent.length - 1;
                                    cmd.Right === "content" ?
                                        handleWheel(e, "Right", index, max, setIndex, () => updateGlyphIndex("Right", font, contentIndex, setGlyphIndex)) :
                                        handleWheel(e, "Right", index, max, setIndex, () => updateContentIndex("Right", font, glyphIndex, setContentIndex))
                                }}
                        />
                    </div>
                </div>
                }
            </div>
   */}